apiVersion: v1
kind: Namespace
metadata:
  name: orders
  labels:
    purpose: enterprise-labs
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders-test
  labels:
    purpose: enterprise-labs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-reconciler
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orders-reconciler
  namespace: orders
rules:
  - apiGroups: [""]
    resources: [configmaps, services, serviceaccounts]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [keda.sh]
    resources: [scaledobjects, triggerauthentications]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [azmonitoring.coreos.com]
    resources: [podmonitors]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [secrets-store.csi.x-k8s.io]
    resources: [secretproviderclasses]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orders-reconciler
  namespace: orders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orders-reconciler
subjects:
  - kind: ServiceAccount
    name: orders-reconciler
    namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orders-reconciler
  namespace: orders-test
rules:
  - apiGroups: [""]
    resources: [configmaps, services, serviceaccounts]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orders-reconciler
  namespace: orders-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orders-reconciler
subjects:
  - kind: ServiceAccount
    name: orders-reconciler
    namespace: flux-system
