apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: kaito-phi4-mini
  namespace: kaito-lab
resource:
  count: 1
  instanceType: Standard_NC24ads_A100_v4
  labelSelector:
    matchLabels:
      kaito-lab: phi4-mini
inference:
  preset:
    name: phi-4-mini-instruct
