apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-api
  namespace: orders
  annotations:
    azure.workload.identity/client-id: __API_CLIENT_ID__
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-worker
  namespace: orders
  annotations:
    azure.workload.identity/client-id: __WORKER_CLIENT_ID__
automountServiceAccountToken: false

